add STAC notebooks
brazil-data-cube/jupyter-gallery pull request #2
Opened 2020-11-04 22:40 UTC by marujore

2020-11-04 22:52 UTC, OldLipe approved these changes

2020-11-05 00:37 UTC, gqueiroz approved these changes

2020-11-05 00:40 UTC, gqueiroz requested changes
Please:
- Rename `image-difference-using-stac.ipynb` to `stac-image-difference.ipynb`.

- Rename `image-threshold-using-stac.ipynb` to `stac-image-threshold.ipynb`.

- Rename `ndvi-calculation-using-stac.ipynb` to `stac-ndvi-calculation.ipynb`.

2020-11-05 03:20 UTC, marujore commented
> Please:
> 
> * Rename `image-difference-using-stac.ipynb` to `stac-image-difference.ipynb`.
> * Rename `image-threshold-using-stac.ipynb` to `stac-image-threshold.ipynb`.
> * Rename `ndvi-calculation-using-stac.ipynb` to `stac-ndvi-calculation.ipynb`.

Done

2020-11-05 11:35 UTC, gqueiroz approved these changes

2020-11-05 11:35 UTC, gqueiroz commented on Python/wtss/wtss-introduction.ipynb
> +<<<<<<< HEAD:wtss/Python/wtss-introduction.ipynb
Please, resolve this merge

2020-11-05 11:35 UTC, merged